### ISSUE TITLE
model name parameter after finetuning

### ISSUE THREAD

**Issue by eshrager** [scaleapi/llm-engine#143]
in the inference script for a finetune model, there's a model parameter:
```python
from llmengine import Completion

response = Completion.create(
    model="llama-2-7b",
    prompt="Do you offer in-flight Wi-fi?",
    max_new_tokens=100,
    temperature=0.2,
)
print(response.json())
``` 
inserting the name of the finetune from the get() method as described in the documentation throws an error "NotFoundError: The specified endpoint could not be found.". 

what should the model name be?

**Comment by yixu34** [comment]
Thanks for flagging! We'll be pushing out a fix in the next day or so.

The workaround right now is to list your Models and find one that has a timestamp in its name that lines up with when you created the finetune: https://scaleapi.github.io/llm-engine/api/python_client/#llmengine.model.Model.list

**Comment by eshrager** [comment]
great! i tried what you suggest but listing the models gives the same names as when you start a finetune and those are the names which don't work.

**Comment by seanshi-scale** [comment]
For the workaround, you'll need to wait until the finetune is completed. In any case https://github.com/scaleapi/llm-engine/pull/145 should fix the issue for `FineTune.get()`. There is a separate server change that I'll need to do to get `.list()` to show model names but that should be in by tomorrow.

**Comment by seanshi-scale** [comment]
oops server changes aren't in yet, will close this once those are in

**Comment by seanshi-scale** [comment]
Verified server changes are in, closing

**Comment by eshrager** [comment]
Still having the exact same issue.

**Comment by seanshi-scale** [comment]
I just pushed another version of the client on pypi (0.0.0b5), that should contain the new `fine_tuned_model` field.
