### ISSUE TITLE
GKE Helm deployment

### ISSUE THREAD

**Issue by brosand** [scaleapi/llm-engine#157]
Is there any thought/desire to setup a helm chart for gke deployment as well?

**Comment by yixu34** [comment]
Hi @brosand , our initial self-hosting deliverable is going to be a fully-contained helm chart that points to k8s-native dependencies (e.g. postgres running on k8s). You can follow along at #141. Once that's in place, presumably you can run on GKE as well. There may be some kinks to iron out at first.

**Comment by brosand** [comment]
Awesome thanks! While I'm feature requesting -- do you have any latency testing benchmarks available? Particularly interested in how this engine compares to engines such as https://github.com/huggingface/text-generation-inference

**Comment by yixu34** [comment]
Oh we use text-generation-inference under the hood (see https://github.com/scaleapi/llm-engine/blob/b2588eac37af8cc1a72bcb91dc659593ffbf502e/server/llm_engine_server/domain/use_cases/llm_model_endpoint_use_cases.py#L230), so you can expect comparable numbers.

The main thing we're offering here is a helm chart with k8s resources to help with scaling, etc.

In terms of performance, we generally try to patch text-generation-inference first, and update our own server code only when needed.
