### ISSUE TITLE
Remove `status` and `traceback` from completion response on the server

### ISSUE THREAD

**Issue by yixu34** [scaleapi/llm-engine#159]
We removed this from our internal version (we'll be moving to public repo-first development soon!), we just need to remove from the public repo too: https://github.com/scaleapi/llm-engine/blob/b2588eac37af8cc1a72bcb91dc659593ffbf502e/server/llm_engine_server/common/dtos/llms.py#L117-L119

**Comment by saiatmakuri** [comment]
Done as part of https://github.com/scaleapi/llm-engine/pull/214
