### ISSUE TITLE
[Lora] Allow more Lora hyperparams

### ISSUE THREAD

**Issue by sam-scale** [scaleapi/llm-engine#163]
Allow `r` and `alpha` to be set in `Create` request

**Comment by saiatmakuri** [comment]
All configs in the [PeftConfig class](https://huggingface.co/docs/peft/main/en/quicktour#peftconfig) are supported to be passed in as `hyperparameters`! Note that the name of the param is `lora_alpha` instead of `alpha`.

e.g. 
```
FineTune.create(hyperparams={"peft_config": {"lora_alpha": 32, "r": 8}})
```
