### ISSUE TITLE
Llama-2-70B support

### ISSUE THREAD

**Issue by yixu34** [scaleapi/llm-engine#166]
Current [Model Zoo](https://scaleapi.github.io/llm-engine/model_zoo/) page doesn't support llama 2 70b:
![image](https://github.com/scaleapi/llm-engine/assets/2041983/71fec037-8cc8-463f-9c45-0c2cef05d652)

**Comment by yixu34** [comment]
cc @goodsidescale

**Comment by bin** [comment]
Second this

**Comment by yixu34** [comment]
@bin Thanks for your interest! We're in the process of getting this up and ready. ETA should be within the next week or so.

Can you say more about your use case? Just a reminder that our hosted APIs are more for evaluation purposes, at least at this time.

**Comment by bin** [comment]
Glad to hear this.  Use case is nothing critical, just a simple chatbot we'd like to have fine-tuned on a specific corpus of information.  Should be pretty low usage.  Training data is good, Q&A with high-quality sourced answers in the 250 word range.  OpenAI, in its infinite wisdom, has declined to make chat-specific models available for fine-tuning, and I don't really feel like paying to fine-tune text-davinci-003 on a public RHLF dataset then our own specific stuff.

**Comment by yunfeng-scale** [comment]
We now have a public Llama 70b model to play with, fine tune is coming up

**Comment by saiatmakuri** [comment]
Fine-tuning is now available for llama-2-70b. However, please take of note of https://github.com/scaleapi/llm-engine/issues/233: while you can create fine-tunes, the models will be unavailable to serve traffic.
