### ISSUE TITLE
Model ids =/= Fine Tune Id?

### ISSUE THREAD

**Issue by sam-scale** [scaleapi/llm-engine#167]

**Comment by saiatmakuri** [comment]
Addressed as part of https://github.com/scaleapi/llm-engine/pull/214 with https://github.com/scaleapi/llm-engine/blob/c4395e9962c8f414c4efb601bf75e62413914a90/model-engine/model_engine_server/domain/use_cases/llm_fine_tuning_use_cases.py#L38
