### ISSUE TITLE
FineTune.get_events errors when there are no FineTune events yet

### ISSUE THREAD

**Issue by rkaplan** [scaleapi/llm-engine#169]
I would expect this to instead return an empty list of events.

<img width="1088" alt="image" src="https://github.com/scaleapi/llm-engine/assets/1389330/f34bb3ae-7c15-4550-918e-b453ec2dcb66">

**Comment by rkaplan** [comment]
Update: after waiting a few minutes, now it returns an empty array: 
<img width="421" alt="image" src="https://github.com/scaleapi/llm-engine/assets/1389330/d7adcc65-8061-4964-a9fa-2f2ca44f3335">

But it should return an empty array immediately after FineTune creation.

**Comment by yixu34** [comment]
An internal PR was merged for this (we're working on making this repo public-only!); pending deploy today.

**Comment by seanshi-scale** [comment]
Internal server changes have been deployed, closing
