### ISSUE TITLE
FineTune.create - NotFoundError (API endpoint seems to through 404)

### ISSUE THREAD

**Issue by f-linus** [scaleapi/llm-engine#170]
When calling FineTune.create with an arbitrary model and CSV a "NotFoundError" is thrown. When investigating, the Scale AI Spellbook API endpoint at https://api.spellbook.scale.com/v1/llm/fine-tune throws an 404.

Used version: 0.0.0b5

Code:
```Pyhon
from llmengine import FineTune
import os
import yaml

if __name__ == "__main__":
    with open("environments/spellbook_api_key.yaml", "r") as stream:
        os.environ.update(yaml.safe_load(stream))

    response = FineTune.create(
        model="llama-2-7b",
        training_file="storage.googleapis.com/llama2-finetune-test/finetune_dataset.csv",
    )

    print(response.json())
```

Error:
![image](https://github.com/scaleapi/llm-engine/assets/84272959/1d25931e-31b7-4f4f-bad0-0047fe016e51)

**Comment by KensingtonOscupant** [comment]
Seeing this too  :/

**Comment by yixu34** [comment]
Looking into it

**Comment by f-linus** [comment]
Error still persists after upgrading to 0.0.0.b7

**Comment by yixu34** [comment]
I'm going to close this out for now - @f-linus feel free to open if you're seeing the issue persist, after accounting for the backslash in the path.
