### ISSUE TITLE
Example ScienceQA fine-tuning notebook has no documentation for how to install dependencies

### ISSUE THREAD

**Issue by rkaplan** [scaleapi/llm-engine#172]
https://github.com/scaleapi/llm-engine/blob/main/examples/finetune_llama_2_on_science_qa.ipynb

**Comment by ian-scale** [comment]
fixed to add dependency requirements and pip installs, see https://github.com/scaleapi/llm-engine/commit/7d6a9c3476ccd49360c71c8c83f6c06f9cee800d
