### ISSUE TITLE
Import completion error

### ISSUE THREAD

**Issue by necromancer1** [scaleapi/llm-engine#182]
`from llmengine import Completion
`
ImportError: cannot import name 'Completion' from partially initialized module 'llmengine' (most likely due to a circular import)

pip list:

scale-llm-engine   0.0.0b7

**Comment by ian-scale** [comment]
I can't replicate your import issue on my machine with 0.0.0b7, could you provide some more information?

**Comment by ian-scale** [comment]
I'm going to close this issue now assuming that there's not anything else that needs to be done here.
