### ISSUE TITLE
Error: Internal Server Error: <class 'AttributeError'>: 'CreateFineTuneResponse' object has no attribute 'artifact_id'

### ISSUE THREAD

**Issue by ashutoshrana171** [scaleapi/llm-engine#272]
Hi Team,

Can you provide a quick solution to the internal server error?
I was trying to fine tune and get this error using my code as well as the code provided in the llm engine documents.

Code:
---------------------------------------------------------------------------
create_fine_tune_response = FineTune.create(
    model="llama-2-7b",
    training_file="https://scale-demo-datasets.s3.us-west-2.amazonaws.com/sports/sports_training_dataset.csv",
    validation_file=None,
    hyperparameters={"epochs": "1", "lr": "0.0002"},
    suffix="my-first-fine-tune"
)

fine_tune_id = create_fine_tune_response.fine_tune_id

Error:
---------------------------------------------------------------------------
UnknownError                              Traceback (most recent call last)
[<ipython-input-17-8fed3eb646ef>](https://localhost:8080/#) in <cell line: 1>()
----> 1 create_fine_tune_response = FineTune.create(
      2     model="llama-2-7b",
      3     training_file="https://scale-demo-datasets.s3.us-west-2.amazonaws.com/sports/sports_training_dataset.csv",
      4     validation_file=None,
      5     hyperparameters={"epochs": "1", "lr": "0.0002"},

1 frames
[/usr/local/lib/python3.10/dist-packages/llmengine/api_engine.py](https://localhost:8080/#) in post_sync(cls, resource_name, data, timeout)
    105         )
    106         if response.status_code != 200:
--> 107             raise parse_error(response.status_code, response.content)
    108         payload = response.json()
    109         return payload

UnknownError: Internal Server Error: <class 'AttributeError'>: 'CreateFineTuneResponse' object has no attribute 'artifact_id'

**Comment by yixu34** [comment]
Hi @ashutoshrana171 , thanks for flagging. We'll be looking into this.

**Comment by ashutoshrana171** [comment]
Hi @yixu34 , do you have any workaround in the meantime or a timeline when this issue can be fixed?

**Comment by ian-scale** [comment]
@ashutoshrana171 One temporary workaround is to use curl requests, i.e. 

`curl --location 'https://model-engine.ml-serving-internal.scale.com/v1/llm/fine-tunes' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic yourapikey' \
--data '{
    "model": "llama-2-7b",
    "training_file": "https://scale-demo-datasets.s3.us-west-2.amazonaws.com/sports/sports_training_dataset.csv",
    "hyperparameters": {"epochs": "1", "lr": "0.0002"},
    "suffix": "my-first-fine-tune"
}'`

for the basic auth, you can take your spellbook api key as the username and no password and then convert it using a generator like the one [here](https://www.debugbear.com/basic-auth-header-generator).

**Comment by ian-scale** [comment]
This should be fixed now in `llm-engine` as well, so the workaround should no longer be necessary. Thanks for reaching out and pointing out this issue! Let me know if you are able to successfully start a fine-tuning job and then I'll close out this issue.
