### ISSUE TITLE
Add support for Mistral-7B in the Completions API

### ISSUE THREAD

**Issue by yixu34** [scaleapi/llm-engine#301]
## Feature Request

**What is the problem you're currently running into?**

Add Mistral-7B to LLM Engine.

**Why do you want this feature?**
A clear and concise description of why you want the feature.

https://mistral.ai/news/announcing-mistral-7b/

Benchmarks seem impressive:
![image](https://github.com/scaleapi/llm-engine/assets/2041983/e65202d4-637f-4b8f-bf29-0446d7a1b55a)

**Describe the solution you'd like**

Mistral-7B should appear in the model zoo.

**Describe alternatives you've considered**

N/A

**Additional context**

### Prioritization

- **Does this feature block you from using the project?**
  - [ ] Yes
  - [X] No

- **How many users will benefit from this feature?**
  - [ ] Just me
  - [ ] Few people might benefit
  - [X] Many users will love it!

- **Complexity**
  - [X] I believe it's a simple feature to implement
  - [ ] It might require some effort to implement
  - [ ] It's probably complex, and might take significant effort

---

Thank you for your contribution to `llm-engine`. Please ensure you've given the feature considerable thought before submitting it. Once your feature request is accepted, and you're interested in building it, please mention it so that the maintainers can guide you!

**Comment by yixu34** [comment]
Just need a vLLM version bump, see https://github.com/vllm-project/vllm/issues/1199

**Comment by ian-scale** [comment]
This is now done. Users can send Completion calls to mistral-7b and mistral-7b-instruct.
