### ISSUE TITLE
Add support for Mistral in the FineTune API

### ISSUE THREAD

**Issue by ian-scale** [scaleapi/llm-engine#308]
## Feature Request

**What is the problem you're currently running into?**
We don't yet have mistral models in the FineTune API.

**Why do you want this feature?**
A clear and concise description of why you want the feature.
Mistral outperforms `llama-2-7b`, so it should be at least equally popular for finetuning.

**Describe the solution you'd like**
Add Mistral models (`mistral-7b` and `mistral-7b-instruct`) to the FineTune API so that users can call 
```
FineTune.create(model="mistral-7b", ...)
```
**Describe alternatives you've considered**

**Additional context**

### Prioritization

- **Does this feature block you from using the project?**
  - [ ] Yes
  - [x] No

- **How many users will benefit from this feature?**
  - [ ] Just me
  - [ ] Few people might benefit
  - [x] Many users will love it!

- **Complexity**
  - [ ] I believe it's a simple feature to implement
  - [x] It might require some effort to implement
  - [ ] It's probably complex, and might take significant effort

---

Thank you for your contribution to `llm-engine`. Please ensure you've given the feature considerable thought before submitting it. Once your feature request is accepted, and you're interested in building it, please mention it so that the maintainers can guide you!

**Comment by yixu34** [comment]
Sunsetting the public demo, also no concrete plans on additional fine-tuning API support in LLM Engine: https://github.com/scaleapi/llm-engine/issues/619
