### ISSUE TITLE
how can we use glue dataset to llama2-7B？

### ISSUE THREAD

**Issue by ZHANGJINKUI** [scaleapi/llm-engine#499]
please tell me the details and how can you get the consequence in the following [https://scale.com/blog/fine-tune-llama-2](url)
please tell me and it's important for me to understand how to learn the llm-engine!
thanks!

**Comment by saiatmakuri** [comment]
Please follow this notebook example - https://github.com/scaleapi/llm-engine/blob/main/examples/finetune_llama_2_on_science_qa.ipynb. Let us know if you run into any issues or have any question!
